// Generated by gencpp from file My_programs_package/addTwoIntRequest.msg
// DO NOT EDIT!


#ifndef MY_PROGRAMS_PACKAGE_MESSAGE_ADDTWOINTREQUEST_H
#define MY_PROGRAMS_PACKAGE_MESSAGE_ADDTWOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace My_programs_package
{
template <class ContainerAllocator>
struct addTwoIntRequest_
{
  typedef addTwoIntRequest_<ContainerAllocator> Type;

  addTwoIntRequest_()
    : a(0)
    , b(0)  {
    }
  addTwoIntRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addTwoIntRequest_

typedef ::My_programs_package::addTwoIntRequest_<std::allocator<void> > addTwoIntRequest;

typedef boost::shared_ptr< ::My_programs_package::addTwoIntRequest > addTwoIntRequestPtr;
typedef boost::shared_ptr< ::My_programs_package::addTwoIntRequest const> addTwoIntRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::My_programs_package::addTwoIntRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::My_programs_package::addTwoIntRequest_<ContainerAllocator1> & lhs, const ::My_programs_package::addTwoIntRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::My_programs_package::addTwoIntRequest_<ContainerAllocator1> & lhs, const ::My_programs_package::addTwoIntRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace My_programs_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::My_programs_package::addTwoIntRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "My_programs_package/addTwoIntRequest";
  }

  static const char* value(const ::My_programs_package::addTwoIntRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::My_programs_package::addTwoIntRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addTwoIntRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::My_programs_package::addTwoIntRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::My_programs_package::addTwoIntRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PROGRAMS_PACKAGE_MESSAGE_ADDTWOINTREQUEST_H
